import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { Armata } from "next/font/google";

const armata = Armata({
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="white">
      <body className={`${armata.className} antialiased white`}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
